steps:
  #Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/jumpmind-sandbox/test-python-repo/my-app', '.']

  #Docker Push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/jumpmind-sandbox/test-python-repo/my-app']
  
  #Store images in Google Artifact Registry
images:
  - us-central1-docker.pkg.dev/jumpmind-sandbox/test-python-repo/my-app
